# Generated by Django 5.2 on 2025-04-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_trials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseevent',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverse_events', to='clinical_trials.participant'),
        ),
        migrations.AddField(
            model_name='participanteligibility',
            name='assessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participanteligibility',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_trials.eligibilitycriteria'),
        ),
        migrations.AddField(
            model_name='participanteligibility',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_assessments', to='clinical_trials.participant'),
        ),
        migrations.AddField(
            model_name='protocoldeviation',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deviations', to='clinical_trials.participant'),
        ),
        migrations.AddField(
            model_name='protocoldeviation',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_deviations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocolversion',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_protocols', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteactivitylog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study',
            name='principal_investigator',
            field=models.ForeignKey(limit_choices_to={'is_investigator': True}, on_delete=django.db.models.deletion.PROTECT, related_name='pi_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor',
            field=models.ForeignKey(limit_choices_to={'is_sponsor': True}, on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siteactivitylog',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='protocolversion',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_versions', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='protocoldeviation',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='participant',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='eligibilitycriteria',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='studyarm',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arms', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='participant',
            name='study_arm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='clinical_trials.studyarm'),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='studydocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocolversion',
            name='document',
            field=models.ForeignKey(limit_choices_to={'document_type': 'protocol'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocol_versions', to='clinical_trials.studydocument'),
        ),
        migrations.AddField(
            model_name='studyphase',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='studysite',
            name='coordinator',
            field=models.ForeignKey(limit_choices_to={'is_coordinator': True}, on_delete=django.db.models.deletion.PROTECT, related_name='site_coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysite',
            name='principal_investigator',
            field=models.ForeignKey(limit_choices_to={'is_investigator': True}, on_delete=django.db.models.deletion.PROTECT, related_name='site_pi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studysite',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='siteactivitylog',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='clinical_trials.studysite'),
        ),
        migrations.AddField(
            model_name='protocoldeviation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviations', to='clinical_trials.studysite'),
        ),
        migrations.AddField(
            model_name='participant',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='clinical_trials.studysite'),
        ),
        migrations.AddField(
            model_name='visit',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinical_trials.participant'),
        ),
        migrations.AddField(
            model_name='visit',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clinical_trials.studysite'),
        ),
        migrations.AddField(
            model_name='visittemplate',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_templates', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='visit',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_trials.visittemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='participanteligibility',
            unique_together={('participant', 'criteria')},
        ),
        migrations.AlterUniqueTogether(
            name='protocolversion',
            unique_together={('study', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studyphase',
            unique_together={('study', 'phase_type')},
        ),
    ]
