# Generated by Django 5.2 on 2025-04-05 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_trials', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='indication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='phase',
            field=models.CharField(blank=True, choices=[('PHASE_0', 'Phase 0'), ('PHASE_1', 'Phase 1'), ('PHASE_2', 'Phase 2'), ('PHASE_3', 'Phase 3'), ('PHASE_4', 'Phase 4')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='study',
            name='target_enrollment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='study',
            name='therapeutic_area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='sponsor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_sponsor': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sponsored_studies', to=settings.AUTH_USER_MODEL),
        ),
    ]
