# Generated by Django 5.2 on 2025-04-05 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_trials', '0004_alter_studyphase_options_studyphase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyphase',
            name='phase_type',
            field=models.CharField(blank=True, choices=[('phase_0', 'Phase 0'), ('phase_1', 'Phase 1'), ('phase_2', 'Phase 2'), ('phase_3', 'Phase 3'), ('phase_4', 'Phase 4')], max_length=20, null=True),
        ),
    ]
