# Generated by Django 5.2 on 2025-04-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_trials', '0002_initial'),
        ('donation_management', '0002_initial'),
        ('recruiting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlog',
            name='contacted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='recruiting.prospect'),
        ),
        migrations.AddField(
            model_name='healthinfo',
            name='prospect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_info', to='recruiting.prospect'),
        ),
        migrations.AddField(
            model_name='demographicinfo',
            name='prospect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='recruiting.prospect'),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='recruiting.prospect'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to='recruiting.prospect'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='donation_management.donor'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='clinical_trials.participant'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='recruiting.prospect'),
        ),
        migrations.AddField(
            model_name='socialmediacampaign',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignmetrics',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='recruiting.socialmediacampaign'),
        ),
        migrations.AddField(
            model_name='studyqualification',
            name='assessed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyqualification',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_qualifications', to='recruiting.prospect'),
        ),
        migrations.AddField(
            model_name='studyqualification',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospect_qualifications', to='clinical_trials.study'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignmetrics',
            unique_together={('campaign', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='studyqualification',
            unique_together={('prospect', 'study')},
        ),
    ]
