# Generated by Django 5.2 on 2025-04-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_trials', '0002_initial'),
        ('donation_management', '0002_initial'),
        ('sponsor_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customsamplerequest',
            name='researcher',
            field=models.ForeignKey(limit_choices_to={'is_researcher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sample_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsamplerequest',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_management.sampletype'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='sponsor_portal.dashboard'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_management.sampletype'),
        ),
        migrations.AddField(
            model_name='ordersample',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_samples', to='sponsor_portal.orderitem'),
        ),
        migrations.AddField(
            model_name='ordersample',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='donation_management.sample'),
        ),
        migrations.AddField(
            model_name='protocoldraft',
            name='sponsor',
            field=models.ForeignKey(limit_choices_to={'is_sponsor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='protocol_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocolreview',
            name='protocol_draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='sponsor_portal.protocoldraft'),
        ),
        migrations.AddField(
            model_name='protocolreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocol_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recruitmentmetrics',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_metrics', to='clinical_trials.studysite'),
        ),
        migrations.AddField(
            model_name='recruitmentmetrics',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_metrics', to='clinical_trials.study'),
        ),
        migrations.AddField(
            model_name='researcherprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sampleorder',
            name='custom_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='sponsor_portal.customsamplerequest'),
        ),
        migrations.AddField(
            model_name='sampleorder',
            name='researcher',
            field=models.ForeignKey(limit_choices_to={'is_researcher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='sample_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordersample',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='sponsor_portal.sampleorder'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sponsor_portal.sampleorder'),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='recruitmentmetrics',
            unique_together={('study', 'site', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='ordersample',
            unique_together={('order', 'sample')},
        ),
    ]
