# Generated by Django 5.2 on 2025-04-07 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_trials', '0006_participant_address_participant_arm_and_more'),
        ('donation_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationappointment',
            name='needs_review',
            field=models.BooleanField(default=False, help_text="Indicates if this appointment needs review due to donor's study participation"),
        ),
        migrations.AddField(
            model_name='donationappointment',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationappointment',
            name='review_status',
            field=models.CharField(choices=[('not_needed', 'Not Needed'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_needed', max_length=20),
        ),
        migrations.AddField(
            model_name='donationappointment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donor',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_record', to='clinical_trials.participant'),
        ),
    ]
